name: EKS Cluster Creation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write      

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
    - name: Terraform Plan

      run: terraform plan -out=tfplan
      working-directory: ./terraform

  wait-for-approval:
    name: Wait for Approval
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: gamal-elhaddad
        minimum-approvals: 1
        issue-title: "Approve Terraform Apply"
        issue-body: "Please approve or deny the apply step for the Terraform plan."  

  terraform-apply:
    name: Terraform Apply
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1


    - name: Terraform Apply
      run: terraform apply 
      working-directory: ./terraform
